export const SITE_URL = 'https://example.com'
export const SITE_TITLE = 'Syenite'
export const SITE_DESCRIPTION = 'Blog engine with SvelteKit + Obsidian'
export const DEFAULT_OG_IMAGE = SITE_URL + '/og.jpeg'
export const AUTHOR = 'breadthe'
export const AUTHOR_URL = 'https://github.com/breadthe'
export const AUTHOR_TWITTER_HANDLE = ''
